In [14]:
import pandas as pd
import os
import glob
  
  
# use glob to get all the csv files 
# in the folder
path = "./FAWN_Data_Daily_Sep23"


csv_files = glob.glob(os.path.join(path, "*.csv"))
csv_files.sort()
print(csv_files)

['./FAWN_Data_Daily_Sep23/1997_daily.csv', './FAWN_Data_Daily_Sep23/1998_daily.csv', './FAWN_Data_Daily_Sep23/1999_daily.csv', './FAWN_Data_Daily_Sep23/2000_daily.csv', './FAWN_Data_Daily_Sep23/2001_daily.csv', './FAWN_Data_Daily_Sep23/2002_daily.csv', './FAWN_Data_Daily_Sep23/2003_daily.csv', './FAWN_Data_Daily_Sep23/2004_daily.csv', './FAWN_Data_Daily_Sep23/2005_daily.csv', './FAWN_Data_Daily_Sep23/2006_daily.csv', './FAWN_Data_Daily_Sep23/2007_daily.csv', './FAWN_Data_Daily_Sep23/2008-1.csv', './FAWN_Data_Daily_Sep23/2008-2.csv', './FAWN_Data_Daily_Sep23/2009-1.csv', './FAWN_Data_Daily_Sep23/2009-2.csv', './FAWN_Data_Daily_Sep23/2010-1.csv', './FAWN_Data_Daily_Sep23/2010-2.csv', './FAWN_Data_Daily_Sep23/2011-1.csv', './FAWN_Data_Daily_Sep23/2011-2.csv', './FAWN_Data_Daily_Sep23/2012-1.csv', './FAWN_Data_Daily_Sep23/2012-2.csv', './FAWN_Data_Daily_Sep23/2013-1.csv', './FAWN_Data_Daily_Sep23/2013-2.csv', './FAWN_Data_Daily_Sep23/2014-1.csv', './FAWN_Data_Daily_Sep23/2014-2.csv', './FAWN_Data_Daily_Sep23/2015-1.csv', './FAWN_Data_Daily_Sep23/2015-2.csv', './FAWN_Data_Daily_Sep23/2016-1.csv', './FAWN_Data_Daily_Sep23/2016-2.csv', './FAWN_Data_Daily_Sep23/2017-1.csv', './FAWN_Data_Daily_Sep23/2017-2.csv', './FAWN_Data_Daily_Sep23/2018-1.csv', './FAWN_Data_Daily_Sep23/2018-2.csv', './FAWN_Data_Daily_Sep23/2019-1.csv', './FAWN_Data_Daily_Sep23/2019-2.csv', './FAWN_Data_Daily_Sep23/2020-1.csv', './FAWN_Data_Daily_Sep23/2020-2.csv', './FAWN_Data_Daily_Sep23/2021_daily.csv', './FAWN_Data_Daily_Sep23/2022_daily.csv', './FAWN_Data_Daily_Sep23/2023_daily.csv']

In [15]:
# Headers (1997-2020)
# 1997 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 1998 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 1999 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2000 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2001 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2002 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2003 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2004 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2005 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2006 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2007 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,avg_wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2008 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2009 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2010 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2011 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2012 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2013 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2014 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2015 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2016 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2017 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2018 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2019 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations 
# 2020 - StationID,date,avg_temp_soil_10cm_C,min_temp_soil_10cm_C,max_temp_soil_10cm_C,avg_temp_air_60cm_C,min_temp_air_60cm_C,max_temp_air_60cm_C,avg_temp_air_2m_C,min_temp_air_2m_C,max_temp_air_2m_C,avg_temp_air_10m_C,min_temp_air_10m_C,max_temp_air_10m_C,avg_rh_2m_pct,avg_temp_dp_2m_C,min_temp_dp_2m_C,max_temp_dp_2m_C,sum_rain_2m_inches,avg_wind_speed_10m_mph,wind_speed_max_10m_mph,wind_direction_10m_deg,avg_rfd_2m_wm2,trf_2m_MJm2,ETo_grass_mm,num_observations
# 2021 - StationID,Date Time,Soil Temp (C) Avg,Soil Temp (C) Min,Soil Temp (C) Max,Temp @ 60cm (C) Avg,Temp @ 60cm (C) Min,Temp @ 60cm (C) Max,Temp @ 2m (C) Avg,Temp @ 2m (C) Min,Temp @ 2m (C) Max,Temp @ 10m (C) Avg,Temp @ 10m (C) Min,Temp @ 10m (C) Max,Relative Humidity (%) Avg,Dew Point Temp (C) Avg,Dew Point Temp (C) Min,Dew Point Temp (C) Max,Rainfall Amount (in) Sum,Wind Speed (mph) Avg,Wind Speed (mph) Max,Wind Direction (deg) Avg,Solar Radiation (w/m2) Avg,Solar Radiation (MJ/m2) Sum,ETo Grass (mm) Avg,Number of Observations
# 2022 - StationID,Date Time,Soil Temp (C) Avg,Soil Temp (C) Min,Soil Temp (C) Max,Temp @ 60cm (C) Avg,Temp @ 60cm (C) Min,Temp @ 60cm (C) Max,Temp @ 2m (C) Avg,Temp @ 2m (C) Min,Temp @ 2m (C) Max,Temp @ 10m (C) Avg,Temp @ 10m (C) Min,Temp @ 10m (C) Max,Relative Humidity (%) Avg,Dew Point Temp (C) Avg,Dew Point Temp (C) Min,Dew Point Temp (C) Max,Rainfall Amount (in) Sum,Wind Speed (mph) Avg,Wind Speed (mph) Max,Wind Direction (deg) Avg,Solar Radiation (w/m2) Avg,Solar Radiation (MJ/m2) Sum,ETo Grass (mm) Avg,Number of Observations
# 2023 - StationID,Date Time,Soil Temp (C) Avg,Soil Temp (C) Min,Soil Temp (C) Max,Temp @ 60cm (C) Avg,Temp @ 60cm (C) Min,Temp @ 60cm (C) Max,Temp @ 2m (C) Avg,Temp @ 2m (C) Min,Temp @ 2m (C) Max,Temp @ 10m (C) Avg,Temp @ 10m (C) Min,Temp @ 10m (C) Max,Relative Humidity (%) Avg,Dew Point Temp (C) Avg,Dew Point Temp (C) Min,Dew Point Temp (C) Max,Rainfall Amount (in) Sum,Wind Speed (mph) Avg,Wind Speed (mph) Max,Wind Direction (deg) Avg,Solar Radiation (w/m2) Avg,Solar Radiation (MJ/m2) Sum,ETo Grass (mm) Avg,Number of Observations

In [16]:
from datetime import datetime
import csv



# Get columns: 0 (Station ID), 1 (date), 8 (avg temperature 2m), 14 (avg relative humidity 2m), 
# 18 (rain 2m sum), 23 (solar radiation 2m sum)
# Parse date formats to Date (YYYY-MM-DD) and Time (HH:MM:SS)

for file in csv_files:
    
    df = pd.read_csv(file)
    
    print("Columns: "+df.columns[0]+", "+df.columns[1]+", "+ df.columns[8]+", "
          +df.columns[14]+", "+df.columns[18]+", "+df.columns[23])

Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, date, avg_temp_air_2m_C, avg_rh_2m_pct, sum_rain_2m_inches, trf_2m_MJm2
Columns: StationID, Date Time, Temp @ 2m (C) Avg, Relative Humidity (%) Avg, Rainfall Amount (in) Sum, Solar Radiation (MJ/m2) Sum
Columns: StationID, Date Time, Temp @ 2m (C) Avg, Relative Humidity (%) Avg, Rainfall Amount (in) Sum, Solar Radiation (MJ/m2) Sum
Columns: StationID, Date Time, Temp @ 2m (C) Avg, Relative Humidity (%) Avg, Rainfall Amount (in) Sum, Solar Radiation (MJ/m2) Sum

In [17]:
from datetime import datetime

big_df = pd.DataFrame()
dfs = []

# Parse date formats to Date (YYYY-MM-DD)

for file in csv_files:
    
    df = pd.read_csv(file)
    #print(len(df))
    dfFiltered = df.iloc[:,[0,1,8,14,18,23]]
    dfFiltered.columns = ['StationID', 'Date_raw', 'Temperature', 'RelatHumidity', 'Rainfall', 'SolarRad']
    dfFiltered.insert(loc = 2, column = 'Date', value = "")
    
    
    # ***********************************
    # 2022 to 2023
    # Date format: YYYY-MM-DD HH:MM:SS
    if ( ("2022" in file) or ("2023" in file) ):
        for index, row in dfFiltered.iterrows():
            dateStr = datetime.strptime(row['Date_raw'], '%Y-%m-%d %H:%M:%S')
            dfFiltered.at[index,'Date'] = dateStr.date()
    
    # ***********************************
    # 1997 to 2021
    # Date format: YYYY-MM-DD
    else:
        for index, row in dfFiltered.iterrows():
            dateStr = datetime.strptime(row['Date_raw'], '%Y-%m-%d')
            dfFiltered.at[index,'Date'] = dateStr.date()
            
    
    dfAppend = dfFiltered[["StationID","Date", "Temperature", "RelatHumidity", "Rainfall", "SolarRad"]]
    dfs.append(dfAppend)
    

big_df = pd.concat(dfs, ignore_index=True)
big_df.tail(20)

        StationID        Date  Temperature  RelatHumidity  Rainfall   SolarRad
314784        425  2023-08-12        30.22          80.51      0.00  24.165873
314785        425  2023-08-13        27.96          87.02      0.24  14.606784
314786        425  2023-08-14        29.57          82.79      0.02  25.105716
314787        425  2023-08-15        29.60          80.94      0.00  24.721362
314788        425  2023-08-16        28.14          84.66      0.08  20.669589
314789        425  2023-08-17        27.91          85.61      0.00  18.761571
314790        425  2023-08-18        27.71          84.58      0.04  17.774469
314791        425  2023-08-19        27.67          85.79      0.09  18.036675
314792        425  2023-08-20        28.05          86.26      0.07  14.325336
314793        425  2023-08-21        30.07          75.80      0.00  22.863177
314794        425  2023-08-22        28.57          80.35      0.16  23.766975
314795        425  2023-08-23        28.23          82.44      0.23  24.962022
314796        425  2023-08-24        26.90          89.18      0.11  11.443203
314797        425  2023-08-25        27.73          81.13      0.00  22.717053
314798        425  2023-08-26        27.79          81.52      0.06  21.892716
314799        425  2023-08-27        28.24          86.67      0.31  19.912050
314800        425  2023-08-28        28.82          84.60      0.00  19.431351
314801        425  2023-08-29        28.23          86.06      0.37  17.938980
314802        425  2023-08-30        29.54          81.65      0.24  18.949365
314803        425  2023-08-31        27.82          92.46      0.27  13.172805

In [18]:
big_df.dtypes

StationID          int64
Date              object
Temperature      float64
RelatHumidity    float64
Rainfall         float64
SolarRad         float64
dtype: object

In [19]:
big_df['Date'] = pd.to_datetime(big_df['Date'])
big_df.dtypes

StationID                 int64
Date             datetime64[ns]
Temperature             float64
RelatHumidity           float64
Rainfall                float64
SolarRad                float64
dtype: object

In [20]:
big_df.shape

(314804, 6)

In [21]:
big_df.describe

<bound method NDFrame.describe of         StationID       Date  Temperature  RelatHumidity  Rainfall   SolarRad
0             302 1997-12-12       14.784            NaN     0.252        NaN
1             302 1997-12-13       15.997            NaN     0.098        NaN
2             302 1997-12-14       11.748            NaN     0.280        NaN
3             302 1997-12-15        7.071            NaN     0.185        NaN
4             302 1997-12-16       11.363            NaN     0.000        NaN
...           ...        ...          ...            ...       ...        ...
314799        425 2023-08-27       28.240          86.67     0.310  19.912050
314800        425 2023-08-28       28.820          84.60     0.000  19.431351
314801        425 2023-08-29       28.230          86.06     0.370  17.938980
314802        425 2023-08-30       29.540          81.65     0.240  18.949365
314803        425 2023-08-31       27.820          92.46     0.270  13.172805

[314804 rows x 6 columns]>

In [22]:
# Drop Feb-29 of leap years: 2000, 2004, 2008, 2012, 2016, 2020
# to map "Day of Year" (DOY) between 1 and 365

big_df = big_df.drop(big_df[big_df['Date']=="2000-02-29"].index)
big_df = big_df.drop(big_df[big_df['Date']=="2004-02-29"].index)
big_df = big_df.drop(big_df[big_df['Date']=="2008-02-29"].index)
big_df = big_df.drop(big_df[big_df['Date']=="2012-02-29"].index)
big_df = big_df.drop(big_df[big_df['Date']=="2016-02-29"].index)
big_df = big_df.drop(big_df[big_df['Date']=="2020-02-29"].index)

big_df.shape

(314602, 6)

In [23]:
# DOY: from date (YYYY-MM-DD) to day of year (doy = 1-366)

from datetime import datetime

big_df['doy']=0

for index, row in big_df.iterrows():
    objDate = row['Date']
    day = objDate.timetuple().tm_yday
    year = objDate.timetuple().tm_year
    mon = objDate.timetuple().tm_mon
    
    #2000  2004  2008  2012  2016  2020
    if (year == 2000 or year == 2004 or year == 2008 or year == 2012 or year == 2016 or year == 2020):
        if (mon > 2):
            day = day - 1
    
    big_df.at[index,'doy'] = day

    
big_df.head(30)

    StationID       Date  Temperature  RelatHumidity  Rainfall  SolarRad  doy
0         302 1997-12-12       14.784            NaN     0.252       NaN  346
1         302 1997-12-13       15.997            NaN     0.098       NaN  347
2         302 1997-12-14       11.748            NaN     0.280       NaN  348
3         302 1997-12-15        7.071            NaN     0.185       NaN  349
4         302 1997-12-16       11.363            NaN     0.000       NaN  350
5         302 1997-12-17       12.224            NaN     0.000       NaN  351
6         302 1997-12-18       12.573            NaN     0.000       NaN  352
7         302 1997-12-19       12.689            NaN     0.004       NaN  353
8         302 1997-12-20       15.031            NaN     0.000       NaN  354
9         302 1997-12-21       17.435            NaN     0.000       NaN  355
10        302 1997-12-22       21.913            NaN     0.000       NaN  356
11        302 1997-12-23       21.588            NaN     0.000       NaN  357
12        302 1997-12-24       22.284            NaN     0.000       NaN  358
13        302 1997-12-25       21.462            NaN     0.744       NaN  359
14        302 1997-12-26       17.735            NaN     0.177       NaN  360
15        302 1997-12-27       17.547            NaN     0.339       NaN  361
16        302 1997-12-28        7.340            NaN     0.000       NaN  362
17        302 1997-12-29        9.830            NaN     0.028       NaN  363
18        302 1997-12-30        9.473            NaN     0.000       NaN  364
19        302 1997-12-31       12.584            NaN     0.000       NaN  365
20        303 1997-12-12       15.192         59.363     0.000       NaN  346
21        303 1997-12-13       15.466            NaN     0.000       NaN  347
22        303 1997-12-14       12.354            NaN     0.000       NaN  348
23        303 1997-12-15        7.798            NaN     0.000       NaN  349
24        303 1997-12-16       12.242            NaN     0.008       NaN  350
25        303 1997-12-17       11.748            NaN     0.000       NaN  351
26        303 1997-12-18       12.071            NaN     0.000       NaN  352
27        303 1997-12-19       12.466            NaN     0.000       NaN  353
28        303 1997-12-20       15.159            NaN     0.000       NaN  354
29        303 1997-12-21       17.888            NaN     0.008       NaN  355

In [24]:
big_df.dtypes

StationID                 int64
Date             datetime64[ns]
Temperature             float64
RelatHumidity           float64
Rainfall                float64
SolarRad                float64
doy                       int64
dtype: object

In [25]:
big_df.shape

(314602, 7)

In [26]:
big_df.to_csv('CEA_FAWN_1_AllStations_T_RH_RF_SR_Doy.csv', index=False)